apiVersion: run.cnpg.io/v1
kind: Cluster
metadata:
  name: clinical-ai-cloudrun
spec:
  template:
    spec:
      containers:
      - image: gcr.io/YOUR_GCP_PROJECT/clinical-ai:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: clinical-ai-secrets
              key: openai-api-key
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: clinical-ai-secrets
              key: gemini-api-key
        - name: QDRANT_ENDPOINT
          value: "https://d7bccdb6-4a7b-4e8b-b425-cf76b3221537.europe-west3-0.gcp.cloud.qdrant.io"
        - name: GCP_PROJECT_ID
          value: "YOUR_GCP_PROJECT"
        resources:
          limits:
            cpu: 2
            memory: 2Gi
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: clinical-ai-api
  namespace: default
  annotations:
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/startup-cpu-boost: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      serviceAccountName: clinical-ai-cloudrun
      containers:
      - image: gcr.io/YOUR_GCP_PROJECT/clinical-ai:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          timeoutSeconds: 10
---
apiVersion: iam.cnpg.io/v1
kind: ServiceAccount
metadata:
  name: clinical-ai-cloudrun
  namespace: default
