"""
Data models for the clinical AI multi-agent system
"""
from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict, Any
from datetime import datetime
import uuid
from enum import Enum


class FeedbackType(str, Enum):
    CORRECT = "correct"
    PARTIAL = "partial"
    WRONG = "wrong"


@dataclass
class PatientRecord:
    """Patient identification and demographics"""
    patient_id: str = field(default_factory=lambda: f"PT-{uuid.uuid4().hex[:8]}")
    first_name: str = ""
    last_name: str = ""
    date_of_birth: str = ""  # YYYY-MM-DD
    gender: str = ""
    contact: str = ""
    medical_history: str = ""
    allergies: List[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self):
        return asdict(self)


@dataclass
class MedicalData:
    """Container for medical data across modalities"""
    data_id: str = field(default_factory=lambda: f"DATA-{uuid.uuid4().hex[:8]}")
    patient_id: str = ""
    modality: str = ""  # imaging, audio, text, timeseries
    data_type: str = ""  # X-ray, ECG, etc.
    file_path: str = ""
    file_format: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self):
        return asdict(self)


@dataclass
class AgentMicroReport:
    """Report generated by individual agents"""
    agent_name: str = ""
    agent_id: str = field(default_factory=lambda: f"AGENT-{uuid.uuid4().hex[:8]}")
    modality: str = ""
    findings: str = ""
    entities: Dict[str, Any] = field(default_factory=dict)
    confidence_score: float = 0.0
    evidence: List[str] = field(default_factory=list)
    reasoning_chain: str = ""  # How the LLM arrived at conclusions
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    processing_time_ms: float = 0.0

    def to_dict(self):
        return asdict(self)


@dataclass
class LLMThinkingProcess:
    """Captures LLM's reasoning and thought process"""
    thought_id: str = field(default_factory=lambda: f"THOUGHT-{uuid.uuid4().hex[:8]}")
    step: int = 0
    reasoning: str = ""
    data_used: List[str] = field(default_factory=list)
    intermediate_conclusion: str = ""
    confidence: float = 0.0

    def to_dict(self):
        return asdict(self)


@dataclass
class ConsolidatedReport:
    """Final clinical intelligence summary"""
    report_id: str = field(default_factory=lambda: f"REPORT-{uuid.uuid4().hex[:8]}")
    patient_id: str = ""
    patient_name: str = ""
    visit_date: str = field(default_factory=lambda: datetime.now().isoformat())
    
    # Patient presentation
    chief_complaint: str = ""
    patient_voice: str = ""  # Direct patient quotes/concerns
    
    # Clinical findings
    vital_signs: Dict[str, str] = field(default_factory=dict)
    imaging_findings: str = ""
    lab_results: Dict[str, str] = field(default_factory=dict)
    iot_data_summary: str = ""
    
    # Analysis
    differential_diagnoses: List[Dict[str, Any]] = field(default_factory=list)
    primary_diagnosis: str = ""
    severity: str = ""  # mild, moderate, severe, critical
    
    # Recommendations
    medications: List[Dict[str, str]] = field(default_factory=list)
    investigations_needed: List[str] = field(default_factory=list)
    precautions: List[str] = field(default_factory=list)
    follow_up: str = ""
    
    # Evidence and reasoning
    evidence_summary: str = ""
    llm_reasoning_chain: List[LLMThinkingProcess] = field(default_factory=list)
    source_agents: List[str] = field(default_factory=list)
    confidence_score: float = 0.0
    
    # Metadata
    created_by: str = ""  # Which consolidation method/LLM
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self):
        data = asdict(self)
        data['llm_reasoning_chain'] = [thought.to_dict() if hasattr(thought, 'to_dict') else thought 
                                       for thought in data['llm_reasoning_chain']]
        return data


@dataclass
class DoctorFeedback:
    """Doctor's feedback on the generated report"""
    feedback_id: str = field(default_factory=lambda: f"FB-{uuid.uuid4().hex[:8]}")
    report_id: str = ""
    doctor_name: str = ""
    doctor_id: str = ""
    feedback_type: FeedbackType = FeedbackType.CORRECT
    voice_recording_path: Optional[str] = None
    corrections: str = ""
    reason: str = ""
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self):
        return asdict(self)


@dataclass
class QdrantSearchResult:
    """Result from Qdrant hybrid search"""
    document_id: str = ""
    patient_id: str = ""
    data_type: str = ""
    similarity_score: float = 0.0
    dense_score: float = 0.0
    sparse_score: float = 0.0
    temporal_relevance: float = 1.0
    content_preview: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self):
        return asdict(self)


@dataclass
class ClincalIntelligenceSummary:
    """Master consolidation of all agent reports"""
    cis_id: str = field(default_factory=lambda: f"CIS-{uuid.uuid4().hex[:8]}")
    patient_id: str = ""
    report_id: str = ""
    
    # Merged findings from all agents
    complete_clinical_picture: str = ""
    resolved_contradictions: List[str] = field(default_factory=list)
    
    # Final recommendations
    final_diagnosis: str = ""
    treatment_plan: str = ""
    risk_score: float = 0.0
    ethical_considerations: str = ""
    
    # Multi-language support
    available_languages: List[str] = field(default_factory=list)
    
    # Audit trail
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self):
        return asdict(self)
